### PR TITLE
Makes the text files a bit nicer to read in english

### PR DESCRIPTION
**Pull request by meodai**

### CODE REVIEW

**Comment by rtomasa** [comment]
We are moving all the documentation, help, faq and much more to the official wiki and only in english. Once we finish, we will be happy to get native speakers who can help on improving all the writings.

**Comment by meodai** [comment]
@rtomasa cool I'm happy to help. Will you still merge that? (I also speak French and German just in case)

**Comment by rtomasa** [comment]
My apologies because you took your time on improving all these translations, but many things there are already outdated and are not valid anymore. I suggest you to request access to the wiki and wait until we start updating the same heavily. If you are in the Telegram channel, we will announce there when we feel the content is ready for start applying corrections

**Comment by meodai** [comment]
Oh ok no worries

**Pull request merged**
